<?php
require __DIR__.'/includes/functions.php';
$about=$pdo->query('SELECT * FROM about WHERE id=1')->fetch();
$heroImages=[];
if($about['image']) $heroImages[]=$about['image'];
foreach($pdo->query('SELECT image FROM hero_images ORDER BY sort_order,id')->fetchAll() as $heroImage) $heroImages[]=$heroImage['image'];
if(!$heroImages) $heroImages[]='assets/img/placeholder.svg';
$tours=$pdo->query('SELECT * FROM tours ORDER BY sort_order,id LIMIT 12')->fetchAll();
$reviews=$pdo->query('SELECT * FROM reviews ORDER BY sort_order,id LIMIT 6')->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(setting('site_name'))?></title><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/hero-full-width.css"></head><body>
<header><div class="nav"><a class="logo" href="#"><?=e(setting('site_name'))?></a><nav><a href="#about">About us</a><a href="#tours">Tours</a><a href="#reviews">Reviews</a><a href="#contact">Contact</a></nav><a class="navbtn" href="#contact">Book now</a></div></header>
<main>
<section id="about" class="hero"><div class="hero-image" id="hero-image" style="background-image:url('<?=e($heroImages[0])?>')"></div><div class="hero-overlay"></div><div class="hero-content"><span class="eyebrow"><?=e(setting('hero_eyebrow','PRIVATE TRAVEL • LOCAL EXPERIENCES'))?></span><h1><?=e($about['title'])?></h1><p><?=nl2br(e($about['body']))?></p><a class="btn" href="<?=e($about['button_url'])?>"><?=e($about['button_text'])?> →</a></div></section>
<section id="tours" class="section"><div class="section-title"><span>Tours</span><h2>Choose your experience</h2></div><div class="tour-grid"><?php foreach($tours as $t): ?><article class="tour"><div class="tour-img" style="background-image:url('<?=e($t['image'] ?: 'assets/img/placeholder.svg')?>')"></div><div class="tour-body"><h3><?=e($t['title'])?></h3><p><?=e($t['description'])?></p><?php if($t['price']):?><b><?=e($t['price'])?></b><?php endif;?></div></article><?php endforeach;?></div></section>
<section id="reviews" class="section reviews"><div class="section-title"><span>Feedbacks - our reviews</span><h2>What our guests say</h2></div><div class="review-grid"><?php foreach($reviews as $r): ?><article class="review"><div class="avatar" style="background-image:url('<?=e($r['image'] ?: 'assets/img/avatar.svg')?>')"></div><div><div class="stars"><?=str_repeat('★',max(1,min(5,(int)$r['rating'])))?></div><p>“<?=e($r['review'])?>”</p><strong><?=e($r['name'])?></strong><small><?=e($r['location'])?></small></div></article><?php endforeach;?></div></section>
<section id="contact" class="contact"><div><span class="eyebrow">CONTACT</span><h2>Let's plan your next trip.</h2><p>Send us your wishes and we'll prepare a personal proposal.</p></div><form method="post" action="contact.php"><input name="name" placeholder="Your name" required><input name="email" type="email" placeholder="Email" required><textarea name="message" rows="5" placeholder="Tell us about your trip" required></textarea><button class="btn">Send request</button></form></section>
</main><footer><div><?=e(setting('site_name'))?></div><div><?=e(setting('email'))?> · <?=e(setting('phone'))?></div></footer><?php if(count($heroImages)>1):?><script>const heroImages=<?=json_encode(array_values($heroImages),JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT)?>;let heroImageIndex=0;setInterval(()=>{heroImageIndex=(heroImageIndex+1)%heroImages.length;document.getElementById('hero-image').style.backgroundImage=`url("${heroImages[heroImageIndex]}")`;},3000);</script><?php endif;?></body></html>
