CREATE TABLE IF NOT EXISTS admins (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS about (id INT PRIMARY KEY, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, button_text VARCHAR(100) DEFAULT 'Discover more', button_url VARCHAR(255) DEFAULT '#tours', image VARCHAR(255) DEFAULT '');
CREATE TABLE IF NOT EXISTS tours (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT, price VARCHAR(100), image VARCHAR(255), sort_order INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reviews (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, location VARCHAR(150), review TEXT NOT NULL, rating TINYINT DEFAULT 5, image VARCHAR(255), sort_order INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO settings(name,value) VALUES ('site_name','Your Travel Company'),('email','info@example.com'),('phone','+994 50 000 00 00') ON DUPLICATE KEY UPDATE value=value;
INSERT INTO about(id,title,body,button_text,button_url,image) VALUES (1,'Discover your next journey','Create memorable private tours and experiences with a local travel team. Add your own text, images and destinations from the admin panel.','Explore tours','#tours','') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO tours(title,description,price,sort_order) VALUES ('City Discovery','A private city tour tailored to your interests.','From €80',1),('Mountain Escape','Nature, viewpoints and local experiences.','From €120',2),('Cultural Journey','Museums, heritage and authentic local stories.','From €100',3),('Food & Wine','Taste local cuisine with a private guide.','From €90',4),('Private Adventure','A flexible full-day itinerary for your group.','From €140',5);
INSERT INTO reviews(name,location,review,rating,sort_order) VALUES ('Anna','Germany','Amazing organization and a wonderful guide. Everything was smooth from start to finish.',5,1),('Michael','Belgium','Great communication, beautiful places and a very personal experience.',5,2),('Sophie','France','We loved the flexibility and attention to detail.',5,3),('Daniel','Netherlands','A memorable trip with excellent service.',5,4);
